services:
  writer-copilot:
    build: .
    container_name: cwi-app
    ports:
      - "3081:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    environment:
      NODE_OPTIONS: --max-old-space-size=192
